### ISSUE TITLE
Update MetaBrainz.Common.Json Error

### ISSUE THREAD

**Issue by RolandoKRC** [Zastai/MetaBrainz.MusicBrainz#2]
Update MetaBrainz.Common.Json to version 2 and now I get an error when initializing the Query class, attached example and error. 
Thank you very much for the help in advance.

busquedaBrainz = new Query("Radio.MusicBrainz", "1.0", "rkrc@prueba.com");

Error:
System.TypeInitializationException
  HResult=0x80131534
  Mensaje = Se produjo una excepción en el inicializador de tipo de 'MetaBrainz.MusicBrainz.Query'.
  Origen = MetaBrainz.MusicBrainz
  Seguimiento de la pila:
   at MetaBrainz.MusicBrainz.Query..ctor(String application, String version, String contact)
   at Radio.Admon.Libreria.FrmArtista.Inicializar() in C:\Users\lenovo\Documents\Visual Studio 2017\Projects\Radio\Radio.Admon\Libreria\FrmArtista.cs:line 86
   at Radio.Admon.Libreria.FrmArtista..ctor() in C:\Users\lenovo\Documents\Visual Studio 2017\Projects\Radio\Radio.Admon\Libreria\FrmArtista.cs:line 36
   at Radio.Admon.FrmMain.TsmLibArtista_Click(Object sender, EventArgs e) in C:\Users\lenovo\Documents\Visual Studio 2017\Projects\Radio\Radio.Admon\FrmMain.cs:line 42
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Radio.Admon.FrmLogin.BtnLogin_Click(Object sender, EventArgs e) in C:\Users\lenovo\Documents\Visual Studio 2017\Projects\Radio\Radio.Admon\FrmLogin.cs:line 60
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Radio.Admon.Program.Main() in C:\Users\lenovo\Documents\Visual Studio 2017\Projects\Radio\Radio.Admon\Program.cs:line 19

Excepción interna 1:
TypeLoadException: No se puede cargar el tipo 'MetaBrainz.Common.Json.Converters.InterfaceConverter`2' del ensamblado'MetaBrainz.Common.Json, Version=2.0.0.0, Culture=neutral, PublicKeyToken=be12cbb629c03021'.

**Comment by Zastai** [comment]
Yes, a new major version indicates that there was an incompatible API change. The MetaBrainz.MusicBrainz you are using references version 1.x; that means there i no guarantee that it will work with version 2.x.
